### ISSUE TITLE
[feature request] Select region for mem ops.

### ISSUE THREAD

**Issue by turoksama** [MaJerle/lwmem#1]
Hello there,
  I tried your lib recently, it's nice although not fully tested yet.
  And I think it is reasonable to add a feature that users can select a specific region to do mem ops because they may have several regions with different sizes, and need to specify the particular one for use.
  Thus, hopefully we can select that region manually.
Many thanks.

**Comment by MaJerle** [comment]
> I tried your lib recently, it's nice although not fully tested yet.
Not tested on your side or?

In fact, this is something I have considered. It would be a good feature since you could split some allocation within internal memory (focus on embedded systems) and maybe larger buffers on external one.

Allocation & reallocation functions would need to accept pointer to region start address then, preventing user to use local variables for region definition.

**Comment by turoksama** [comment]
Not tested on my side, will make it a go very soon.
I used it in embedded systems, here is a situation below:
I have larger buffers on external one, and want another internal one for faster(smaller of course) issues within one lwmem.
Would you like to make it happen?

**Comment by MaJerle** [comment]
I will consider this option as compiler macro (enabled or not on compilation side).

**Comment by turoksama** [comment]
sounds tempting!

**Comment by MaJerle** [comment]
New branch has been added: https://github.com/MaJerle/lwmem/tree/feature/alloc_from_region

It now implements what you have been asking for, at least from basic functionality standpoint. Still some API to be corrected.

```
void *          LWMEM_PREF(malloc_from)(const LWMEM_PREF(region_t)* region, const size_t size);
void *          LWMEM_PREF(calloc_from)(const LWMEM_PREF(region_t)* region, const size_t nitems, const size_t size);
void *          LWMEM_PREF(realloc_from)(const LWMEM_PREF(region_t)* region, void* const ptr, const size_t size);
unsigned char   LWMEM_PREF(realloc_from_s)(const LWMEM_PREF(region_t)* region, void** const ptr, const size_t size);
```

If you, for example use `lwmem_malloc_from(&regions[1], 16)`, it will try to allocate `16` bytes of memory from second region defined in your configuration.

**Comment by MaJerle** [comment]
Also, please note that with current implementation of LwMEM, even if you do a security (for some reason) on one region, algorithm still must have access to all regions, at least during startup to prepare linkedlist internally.

**Comment by turoksama** [comment]
It's a more functional implementation for now. 
Thanks for your hardwork! Cheers.
But what if we can access them completely separated as you've mentioned above?
FYI, I have an idea that they are acting as objects(like a tar ball with separated link table within themselves), lwmem system manage these objects separately, if we need links then renew the link table.
What do you think?

**Comment by MaJerle** [comment]
Purpose of LwMEM regions is to have ability of fragmented memories in embedded systems. Not always you have continuous block of data. You can add for example fast RAM region or external RAM region to one lwmem. Now with `_from` functions, you can also ask LwMEM to allocate memory from specific region.

But to completely separate, we would need to add another layer. LwMEM has an instance indicating *beginning of regions* where allocation starts. In order to have multiple, malloc would need to look something like:

```
malloc(&lwmem_instance, amount_of_bytes);
malloc_from(&lwmem_instance, &region_in_lwmem_instance, number_of_bytes);
```

As you can see, additional parameter is added to indicate instance of Lwmem. Today, this is fixed single region.

See here: https://docs.majerle.eu/projects/lwmem/en/latest/user-manual/how-it-works.html
Start block is now fixed, while for your request, multiple start blocks would be necessary, this would then be a parameter for every operation.

**Comment by MaJerle** [comment]
I decided to add support for multiple instances, each instance supporting multiple regions. `_from` functions will be extended with *lwmem instance*.

**Comment by turoksama** [comment]
Hmm., sounds great! 
I have an issue here:
mem allocated wrong address with region 2 while using _from function,it returns the top address of that region. i registered two regions, first one is located at sdram, the second is located at internal sram. 
please check.

**Comment by MaJerle** [comment]
Why do you believe that this is wrong? You wanted to allocate from region 2, you got region 2. Or am I wrong?

**Comment by MaJerle** [comment]
Here we go. I did some changes:

- `_from` functions have been replace with `_ex`, stands for *extended* for advanced users.
- There is always one default lwmem structure, as if you need lwmem, then anyway you need at least one instance
- Application may create new `lwmem_t` instance and use it as second memory manager. It then must apply new regions for second instance

Code just published

**Comment by turoksama** [comment]
The "top" I mean the end of region. 
I defined that pool in internal sram at 0x10000000, and using _from function for the very first request and much smaller size than the pool's, but returned a pointer valued "0x20030000", that's the end of SRAM and which is nothing to do with that pool.

**Comment by MaJerle** [comment]
Show your code please.
